language: go
sudo: required

services:
  - docker

go:
  - 1.12.x

notifications:
  email:
    on_success: change
    on_failure: always

install:
  - docker pull therecipe/qt:linux
  - go get -v -tags=no_env github.com/therecipe/qt/cmd/...

script:
  - go get -u -v
  - $GOPATH/bin/qtdeploy -docker build linux
